server:
  port: 8888

  # 编码集设置，2.7.8默认编码集就是utf-8
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true

 # 配置数据源
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/blog?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useOldAliasMetadataBehavior=true&allowPublicKeyRetrieval=true
    username: root
    password: a
  application:
      name: myBlog-server

#日志配置
logging:
  level:
    root: warn
    com.*: debug
  file:
    name: /logs/${spring.application.name}.log
  pattern:
    file: myDemo %d{yyyy-MM-dd HH:mm:ss.SSS} %p %C.%M %m %n
  logback:
    rollingpolicy:
      file-name-pattern: /logs/%d{yyyyMMdd}/${spring.application.name}.out.log.%d{yyyy-MM-dd}.%i.gz
      max-file-size: 2KB
      total-size-cap: 1GB
      max-history: 7

# redis配置
redis:
  host: 127.0.0.1
  port: 6379
  lettuce:
    pool:
      max-active: 8 # 最大连接
      max-idle: 8   # 最大空间连接
      min-idle: 0   # 最小空闲连接
      max-wait: 100   # 连接等待时间

mybatis-plus:

  mapper-locations: classpath:mapper/**/*.xml

  type-aliases-package: com.blog.hulk.selfblog.entity,com.blog.hulk.selfblog.transfer



  global-config:

    db-config:
      table-prefix: tbl_

    capital-mode: true

    logic-delete-value: 1
    logic-not-delete-value: 0

  # 分页配置
  pagination:
    enabled: true
    page-size: 10
    reasonable: true
